# Generated by Django 5.1.2 on 2025-10-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
