# Generated by Django 5.1.2 on 2025-10-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_cart_table_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartproduct",
            unique_together=set(),
        ),
    ]
