# Generated by Django 5.1.2 on 2025-10-19 00:24

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_cartproduct_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("vector", pgvector.django.vector.VectorField(dimensions=128)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vectors",
                        to="client.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
